CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	username VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	verifCode VARCHAR(255) NULL,
	verifCodeExpires TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	isActive BOOLEAN DEFAULT false,
	notifMail BOOLEAN DEFAULT true,
	cookieToken CHAR(64),
	cookieExpires DATETIME DEFAULT CURRENT_TIMESTAMP,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE images (
	id INT AUTO_INCREMENT PRIMARY KEY,
	path VARCHAR(255) NOT NULL UNIQUE,
	author INT NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (author) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE likes (
	id INT AUTO_INCREMENT PRIMARY KEY,
	author INT NOT NULL,
	toImage INT NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (author) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (toImage) REFERENCES images(id) ON DELETE CASCADE,
	UNIQUE (author, toImage)
);

CREATE TABLE comments (
	id INT AUTO_INCREMENT PRIMARY KEY,
	author INT NOT NULL,
	message VARCHAR(255) NOT NULL,
	toImage INT NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (author) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (toImage) REFERENCES images(id) ON DELETE CASCADE
);

CREATE TABLE mailQueue (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL,
	subject VARCHAR(255) NOT NULL,
	body TEXT NOT NULL,
	sent BOOLEAN DEFAULT false,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
